version: '3'
services:
  php-fpm:
    build: ./docker/php
    image: cuco/cuco-api:php-fpm
    restart: on-failure
    container_name: cuco-api-php-fpm
    command: php-fpm
    links:
      - mysql
    volumes:
      - ./:/cuco-api
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 9000 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  nginx:
    build: ./docker/nginx
    image: cuco/cuco-api:nginx
    restart: on-failure
    container_name: cuco-api-nginx
    command: nginx -g "daemon off;"
    links:
      - php-fpm
    ports:
      - "${DOCKER_NGINX_PORT}:80"
    volumes:
      - ./:/cuco-api
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 80 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2

  mysql:
    build: ./docker/mysql
    image: cuco/cuco-api:mysql
    restart: on-failure
    container_name: cuco-api-mysql
    command:
      - "--innodb_use_native_aio=0"
    environment:
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DOCKER_MYSQL_USER}
      - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
    ports:
      - ${DOCKER_MYSQL_PORT}:3306
    volumes:
      - ${DOCKER_DATA_PATH}/mysql:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'sh', '-c', 'netstat -an | fgrep 3306 | fgrep -q LISTEN']
      interval: 10s
      timeout: 5s
      retries: 2
